name: CI/CD on master
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "ghcr.io/templatr/nodejs-devenv"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: "Determine release version"
        uses: docker://ghcr.io/codfish/semantic-release-action:v1.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@v1.4.0

      - name: "Build Docker image"
        if: env.RELEASE_VERSION != ''
        run: |
          docker build . -t "$IMAGE_NAME:$RELEASE_VERSION" \
              --label "org.label-schema.schema-version=1.0" \
              --label "org.label-schema.vcs-ref=${GITHUB_SHA}" \
              --label "org.label-schema.vcs-url=https://github.com/${GITHUB_REPOSITORY}" \
              --label "org.label-schema.url=https://github.com/${GITHUB_REPOSITORY}" \
              --label "org.label-schema.vendor=HomeCentr" \
              --label "version=$RELEASE_VERSION" \
              --label "org.label-schema.build-date=$(date '+%F %T')"

      - name: "Tag image as latest"
        if: env.RELEASE_VERSION != ''
        run: "docker tag $IMAGE_NAME:$RELEASE_VERSION $IMAGE_NAME:latest"

      - name: "Log into Docker Hub"
        if: env.RELEASE_VERSION != ''
        run: "echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin"

      - name: "Push versioned image"
        if: env.RELEASE_VERSION != ''
        run: "docker push $IMAGE_NAME:$RELEASE_VERSION"

      - name: "Push latest image"
        if: env.RELEASE_VERSION != ''
        run: "docker push $IMAGE_NAME:latest"