name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

env:
  IMAGE_NAME: "ghcr.io/techcentr/nodejs-devenv"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}

      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@v1.4.0

      - name: Build Docker image
        run: docker build . -t ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.docker_tag }}